### ISSUE TITLE
Installer does not update installed Peekaboo

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV-Installer#25]
Since switchting to setup.py based installation the installer has no way to detect version changes between installed and to-be-installed version. As long as `/opt/peekaboo/bin/peekaboo` exists, Peekaboo will not be updated. Code from playbook:

```
  tasks:
    - name: Install Peekaboo
      command: /opt/peekaboo/bin/python setup.py install
      args:
        chdir: PeekabooAV
        creates: /opt/peekaboo/bin/peekaboo
#      pip:
#        name: peekabooav
#        state: present
```
